cine_en_tus_manos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]

mainapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views



urlpatterns = [
    # URL PUBLICOS
    path('', views.home, name='home'),
    path('nosotros/', views.nostros, name='nosotros'),
    path('detalle_critica/<int:pk>/', views.detalle_critica, name='detalle_critica'),
    path('peliculas/', views.peliculas, name='peliculas'),
    path('mas_y_mas_chismes/', views.mas_y_mas_chismes, name='mas_y_mas_chismes'),
    path('series/', views.series, name='series'),
    path('trailers/', views.trailers, name='trailers'),
    path('noticias/', views.noticias, name='noticias'),
    path('perfil_colaborador/<str:correo>/', views.perfil_colaborador, name='perfil_colaborador'),
    path('buscar/', views.buscar, name='buscar'),

    # URL PRIVADOS
    path('login/', views.login_view, name='login'),
    path('registro_usuario/', views.registro_usuario, name='registro_usuario'),
    path('editar_eliminar_usuario/', views.editar_eliminar_usuario, name='editar_eliminar_usuario'),
    path('actualizar_usuario/<str:correo>/', views.actualizar_usuario, name='actualizar_usuario'),
    path('eliminar_usuario/<str:correo>/', views.eliminar_usuario, name='eliminar_usuario'),
    path('detalle_usuario/<str:correo>/', views.detalle_usuario, name='detalle_usuario'),
    path('perfil/', views.perfil, name='perfil'),
    path('editar_perfil/', views.editar_perfil, name='editar_perfil'),
    path('admin_view/', views.admin_view, name='admin_view'),
    path('publicar_critica/', views.publicar_critica, name='publicar_critica'),
    path('noticia/', views.noticia, name='noticia'),
    path('critica/', views.critica, name='critica'),
    path('criticas_admin/', views.criticas_admin, name='criticas_admin'),
    path('noticias_admin/', views.noticias_admin, name='noticias_admin'),
    path('search_movie/', views.search_movie_view, name='search_movie'),
    path('get_movie_details/', views.get_movie_details_view, name='get_movie_details'),
    path('mis_criticas/', views.mis_criticas, name='mis_criticas'),
    path('mis_noticias/', views.mis_noticias, name='mis_noticias'),
    path('detalle_critica_admin/<int:pk>/', views.detalle_critica_admin, name='detalle_critica_admin'),
    path('detalle_noticia_admin/<int:pk>/', views.detalle_noticia_admin, name='detalle_noticia_admin'),
    path('eliminar_critica/<int:pk>/', views.eliminar_critica, name='eliminar_critica'),
    path('eliminar_noticia/<int:pk>/', views.eliminar_noticia, name='eliminar_noticia'),
    path('recuperar_password/', views.recuperar_password, name='recuperar_password'),
    path('logout/', views.logout_view, name='logout_view'),
    path('logout_and_redirect_home/', views.logout_and_redirect_home, name='logout_and_redirect_home'),

    path('calendario/', views.calendario, name='calendario'),
    path('calendario_admin/', views.calendario_admin, name='calendario_admin'),
    path('obtener_actividades/', views.obtener_actividades, name='obtener_actividades'),
    path('editar_actividad/<int:pk>/', views.editar_actividad, name='editar_actividad'),
    path('detalle_actividad/<int:pk>/', views.detalle_actividad, name='detalle_actividad'),
    

    # URL ADMINISTRADOR
    path('admin_view/', views.admin_view, name='admin_view'),
    path('no_permission/', views.no_permission, name='no_permission'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth.hashers import make_password, check_password
from django.utils import timezone

# Create your models here.
class FotosPerfil(models.Model):
    id = models.AutoField(primary_key=True)
    # direccion = models.CharField(max_length=100)
    direccion = models.ImageField(upload_to='profiles/')
    nombre = models.CharField(max_length=50)
    
class Tipo(models.Model):
    id = models.AutoField(primary_key=True)
    descripcion = models.CharField(max_length=50)

class CategoriaGenero(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50)

class DondeVer(models.Model):
    id = models.AutoField(primary_key=True)
    plataforma = models.CharField(max_length=50) 

class Permisos(models.Model):
    id = models.AutoField(primary_key=True)
    tipo = models.CharField(max_length=100)

class UserManager(BaseUserManager):
    def create_user(self, correo, nombre, password=None, **extra_fields):
        if not correo:
            raise ValueError('El correo debe ser proporcionado')
        email = self.normalize_email(correo)
        user = self.model(correo=email, nombre=nombre, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, correo, nombre, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(correo, nombre, password, **extra_fields)

class User(AbstractBaseUser):
    correo = models.EmailField(primary_key=True)
    nombre = models.CharField(max_length=100)
    password = models.CharField(max_length=128)
    descripcion = models.CharField(max_length=280)
    foto_perfil = models.ForeignKey(FotosPerfil, on_delete=models.CASCADE)
    #permisos = models.CharField(max_length=50)
    permisos = models.ForeignKey(Permisos, on_delete=models.CASCADE)

    last_login = models.DateTimeField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'correo'
    REQUIRED_FIELDS = ['nombre']

    def set_password(self, raw_password):
        self.password = make_password(raw_password)
        self.save()

    def check_password(self, raw_password):
        return check_password(raw_password, self.password)

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

class Critica(models.Model):
    id = models.AutoField(primary_key=True)
    ruta_foto_critica = models.ImageField(upload_to='review/')
    #ruta_foto_critica = models.ImageField(upload_to='review/', default='path/to/default/image.jpg')
    
    nombre = models.CharField(max_length=255)
    sipnosis = models.TextField()
    director = models.CharField(max_length=255)
    escritor = models.CharField(max_length=255)
    reparto = models.CharField(max_length=255)
    ano = models.CharField(max_length=4)
    pais = models.CharField(max_length=100)
    categoria_genero = models.CharField(max_length=255, blank=True, null=True)

    link_trailer = models.CharField(max_length=255, blank=True, null=True)
    nombre_espanol = models.CharField(max_length=255, blank=True, null=True)
    no_capitulos = models.IntegerField(blank=True, null=True)
    critica = models.TextField()
    donde_ver = models.CharField(max_length=255)
    tipo = models.ForeignKey(Tipo, on_delete=models.CASCADE, related_name='criticas')

    user = models.ForeignKey(User, on_delete=models.CASCADE)  # Cambiado de user_id a user
    datetime = models.DateTimeField(default=timezone.now)

    calificacion = models.FloatField(blank=True, null=True)


class FotosCritica(models.Model):
    id = models.AutoField(primary_key=True)
    direccion = models.CharField(max_length=100)
    critica = models.ForeignKey(Critica, on_delete=models.CASCADE)


class Noticia(models.Model):
    id = models.AutoField(primary_key=True)
    ruta_foto_critica = models.ImageField(upload_to='review/')
    nombre = models.CharField(max_length=255)
    descripcion = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # Cambiado de id_user a user
    datetime = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.nombre

class Actividad(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    descripcion = models.TextField()
    datetime = models.DateField()
    estado = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.descripcion} - {self.user.username}"

mainapp/templates/mainapp/admin.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block title %}ADMINISTRADOR{% endblock %}

{% block content %}
<br>

<div class="h1">
    <a class="navbar-brand" href={% url 'admin_view' %} style="color: #AAB7B8;">
        <img src="{% static 'mainapp/images/icon_administrador.png' %}" alt="Logo" width="60" height="48" class="d-inline-block align-text-top">
        ADMINISTRADOR
    </a>
</div>

<br>

<div class='h2' style='color: white;'>Bienvenido, {{ nombre }}!</div>

<br>

<div class="container">
    <div class="h1">Dashboard</div>

    <br>

    <div class="row">
        <div class="col-md-4">
            <div class="d-grid gap-2">
                <a type="button" href="{% url 'editar_eliminar_usuario' %}" class="btn btn-success btn-lg">
                    Cantidad de Colaboradores Registrados        <span class="badge text-bg-secondary">{{ cantidad_usuarios }}</span>
                </a>
            </div>
        </div>
        <div class="col-md-4">
            <div class="d-grid gap-2">
                <a type="button" href="{% url 'criticas_admin' %}" class="btn btn-info btn-lg">
                    Cantidad de Críticas Realizadas         <span class="badge text-bg-secondary">{{ cantidad_criticas }}</span>
                </a>
            </div> 
            <br>
            <div class="d-grid gap-2">
                <a type="button" href="{% url 'calendario_admin' %}" class="btn btn-secondary btn-lg">
                    Cantidad de Actividades Realizadas         <span class="badge text-bg-secondary">{{ cantidad_actividades }}</span>
                </a>
            </div> 
        </div>
        <div class="col-md-4">
            <div class="d-grid gap-2">
                <a type="button" href="{% url 'noticias_admin' %}" class="btn btn-light btn-lg">
                    Cantidad de Noticias Realizadas         <span class="badge text-bg-secondary">{{ cantidad_noticias }}</span>
                </a>
            </div> 
        </div>
    </div>

    <br>
    <br>

    <div class="row mt-4">
        <div class="col-md-6">
            <canvas id="criticasPorUsuario"></canvas>
        </div>
        <div class="col-md-6">
            <canvas id="criticasPorFecha"></canvas>
        </div>
    </div>

    <br>
    <br>

    <div class="row mt-4">
        <div class="col-md-6">
            <canvas id="tiposCritica"></canvas>
        </div>
    </div>

    <br>

</div>

<!-- Incluir Chart.js -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
    // Gráfica 1: Cantidad de críticas realizadas por usuario
    const criticasPorUsuarioCtx = document.getElementById('criticasPorUsuario').getContext('2d');
    const criticasPorUsuarioData = {{ criticas_por_usuario|safe }};
    const criticasPorUsuarioLabels = criticasPorUsuarioData.map(data => data.nombre);
    const criticasPorUsuarioCounts = criticasPorUsuarioData.map(data => data.num_criticas);

    new Chart(criticasPorUsuarioCtx, {
        type: 'bar',
        data: {
            labels: criticasPorUsuarioLabels,
            datasets: [{
                label: 'Cantidad de Críticas',
                data: criticasPorUsuarioCounts,
                backgroundColor: 'rgba(75, 192, 192, 0.2)',
                borderColor: 'rgba(75, 192, 192, 1)',
                borderWidth: 1
            }]
        },
        options: {
            responsive: true,
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });

    // Gráfica 2: Críticas realizadas tomando en cuenta las fechas y horas
    const criticasPorFechaCtx = document.getElementById('criticasPorFecha').getContext('2d');
    const criticasPorFechaData = {{ criticas_por_fecha|safe }};
    const criticasPorFechaLabels = criticasPorFechaData.map(data => data.date);
    const criticasPorFechaCounts = criticasPorFechaData.map(data => data.num_criticas);

    new Chart(criticasPorFechaCtx, {
        type: 'line',
        data: {
            labels: criticasPorFechaLabels,
            datasets: [{
                label: 'Cantidad de Críticas',
                data: criticasPorFechaCounts,
                backgroundColor: 'rgba(153, 102, 255, 0.2)',
                borderColor: 'rgba(153, 102, 255, 1)',
                borderWidth: 1
            }]
        },
        options: {
            responsive: true,
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });

    // Gráfica 3: Cantidad de series, películas, chismes (gráfica de pastel)
    const tiposCriticaCtx = document.getElementById('tiposCritica').getContext('2d');
    const tiposCriticaData = {{ tipos|safe }};
    const tiposCriticaLabels = tiposCriticaData.map(data => data['tipo__descripcion']);
    const tiposCriticaCounts = tiposCriticaData.map(data => data.count);

    new Chart(tiposCriticaCtx, {
        type: 'pie',
        data: {
            labels: tiposCriticaLabels,
            datasets: [{
                label: 'Tipos de Crítica',
                data: tiposCriticaCounts,
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            responsive: true
        }
    });
</script>

{% endblock %}

mainapp/templates/mainapp/detalle_actividad.html
<div class="container">
    <h2>Detalles de la Actividad</h2>
    <p><strong>Descripción:</strong> {{ actividad.descripcion }}</p>
    <p><strong>Fecha:</strong> {{ actividad.datetime }}</p>
    <p><strong>Estado:</strong> {% if actividad.estado %}Realizada{% else %}Pendiente{% endif %}</p>
</div>

mainapp/templates/mainapp/editar_actividad.html
<div class="container">
    <h2>Editar Actividad</h2>
    <form id="editarActividadForm" method="POST" action="{% url 'detalle_actividad' actividad.pk %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Actualizar Actividad</button>
    </form>
</div>

mainapp/templates/mainapp/editar_eliminar_usuario.html
{% extends 'mainapp/base.html' %}

{% block title %}EDITAR O ELIMINAR COLABORADOR{% endblock %}

{% block content %}

{% load static %}
{% load dict_get %}

<div class="h1">
    <a class="navbar-brand" href="{% url 'editar_eliminar_usuario' %}" style="color: #AAB7B8;">
        <img src="{% static 'mainapp/images/icon_editar.png' %}" alt="Logo" width="60" height="60" class="d-inline-block align-text-top">
        <img src="{% static 'mainapp/images/icon_eliminar.png' %}" alt="Logo" width="60" height="60" class="d-inline-block align-text-top">
        EDITAR O ELIMINAR COLABORADOR
    </a>
</div>

<br>

{% if messages %}
    <div class="container mb3">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" style="background: #12a15e">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    </div>
{% endif %}

<br>

<div class="d-grid gap-2">
    <a href="{% url 'registro_usuario'%}" type="button" class="btn btn-light">REGISTRAR NUEVO COLABORADOR</a>
</div>

<br>

{% for usuario in usuarios %}
    {% with forms|dict_get:usuario.correo as form %}
        {% if form %}
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card mb-3" style="color: black;">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="correo" style="color: black; font-weight: bold;">Correo</label>
                            <div class="card">
                                <div class="card-body" style="width: 100%;">
                                    {{ usuario.correo }}
                                </div>
                                <input type="hidden" name="correo" value="{{ usuario.correo }}">
                            </div>
                        </div>
                        {{ form.as_p }}
                        <button type="submit" name="update" class="btn btn-success">Guardar Cambios</button>
                        <button type="submit" name="delete" class="btn btn-danger">Eliminar Colaborador</button>
                    </div>
                </div>
            </form>
            <br>
        {% else %}
            <p>Error al cargar el formulario para {{ usuario.correo }}.</p>
        {% endif %}
    {% endwith %}
{% endfor %}

{% endblock %}

mainapp/templates/mainapp/nosotros.html
{% extends 'mainapp/base.html' %}
{% load static %} <!-- Cargar el tag static -->
{% get_media_prefix as media_prefix %} <!-- Obtener el prefijo de medios -->

{% block title %}NOSOTROS{% endblock %}

{% block content %}

<br>

<div class='h1' style='color: white;'>ACERCA DE CINE EN TUS MANOS</div>

<br>

<div class="row">
    <div class="col-sm-6 mb-3 mb-sm-0">
        <div class="h1">
            Misión
        </div>
        <div class="h3">
            Somos un medio independiente, veraz y confiable, donde tanto cinéfilos como consumidores ocasionales pueden encontrar información actual sobre la industria del cine nacional e internacional.
        </div>
        <br>
        <br>
        <div class="h1">
            Visión
        </div>
        <div class="h3">
            Convertirnos en el medio de referencia para la información cinematográfica, mejorando continuamente nuestro contenido con la inclusión de entrevistas exclusivas, noticias actualizadas y reportajes detallados relacionados con el séptimo arte.
        </div>
    </div>
    <div class="col-sm-6">
        <div class="row row-cols-1 row-cols-md-3 g-4">
            <div class="col">
                <div class="card h-100">
                    <img src="{% static 'mainapp/images/perfil.jpg' %}" class="card-img-top" alt="...">
                </div>
            </div>
            <div class="col">
                <div class="card h-100">
                    <img src="{% static 'mainapp/images/image3.jpg' %}" class="card-img-top" alt="...">
                </div>
            </div>
            <div class="col">
                <div class="card h-100">
                    <img src="{% static 'mainapp/images/logo_invertido.png' %}" class="card-img-top" alt="...">
                </div>
            </div>
        </div>

        <br>

        <div class="card mb-3">
            <img src="{% static 'mainapp/images/portada.jpeg' %}" class="card-img-top" alt="...">
        </div>
    </div>
</div>


<br>
<br>
<br>
<br>


{% endblock %}

mainapp/templates/mainapp/noticia.html
{% extends 'mainapp/base.html' %}
{% load form_extras %}
{% load static %}

{% block title %}CREAR NOTICIA{% endblock %}

{% block content %}

<div class="h1">
    <a class="navbar-brand" href={% url 'noticia' %} style="color: #AAB7B8;">
        <img src="{% static 'mainapp/images/icon_resena.png' %}" alt="Logo" width="60" height="48" class="d-inline-block align-text-top">
        CREAR NOTICIA
    </a>
</div>

<br>

<div class='h2' style='color: white;'>Bienvenido, {{ usuario }}!</div>

<div class='container'>
    <br>
    {% if messages %}
        <div class="container mt-4">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" style="background: #12a15e">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <br>
        <hr>
        <br>

        <div class="mb-3">
            <label for="nombre_espanol" class="form-label">Nombre de la Noticia</label>
            {{ form.nombre|add_attrs:"class=form-control,id=nombre_espanol" }}
        </div>
        <div class="mb-3">
            <label for="critica" class="form-label">Descripcion de la noticia</label>
            {{ form.descripcion|add_attrs:"class=form-control,id=critica,style=height:4rem;" }}
        </div>
        <div class="mb-3">
            <label for="ruta_foto_critica" class="form-label">Selecciona Foto de Noticia</label>
            {{ form.ruta_foto_critica|add_attrs:"class=form-control,id=ruta_foto_critica" }}
        </div>

        <button type="submit" class="btn btn-primary">COMPARTIR NOTICIA</button>
        <br>
        <br>
    </form>
</div>

{% endblock %}

mainapp/templates/mainapp/perfil.html
{% extends 'mainapp/base.html' %}
{% load form_extras %}
{% load static %} <!-- Cargar el tag static -->
{% get_media_prefix as media_prefix %}

{% block title %}PERFIL{% endblock %}

{% block content %}

<div class="h1">
    <a class="navbar-brand" href={% url 'perfil' %} style="color: #AAB7B8;">
        <img src="{% static 'mainapp/images/icon_perfil.png' %}" alt="Logo" width="60" height="60" class="d-inline-block align-text-top">
        PERFIL
    </a>
</div>

<div class='container'>
    <br>

    {% if messages %}
        <div class="container mb3">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" style="background: #12a15e">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row g-2">
            <div class="col-md">
                <div class="form-floating">
                    <div class="mb-3">
                        <div class="card" style="width: 32rem; border-radius: 10px;">
                            <img class="card-img-top" src="{{ usuario.foto_perfil.direccion.url }}" alt="Foto de perfil" style="border-radius: 10px;" id="foto-perfil-preview">
                            <div class="card-body">
                                <h5 class="card-title" style="font-weight: bold;">{{ usuario.nombre }}</h5>
                                <p class="card-text">{{ usuario.correo }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md">
                <div class="form-floating">
                    <div class="mb-3">
                        <label for="inputEmail4" style="color: aliceblue; font-weight: bold;">Tipo de Usuario</label>
                        <div class="card">
                            <div class="card-body" style="width: 100%;">
                                {% if usuario.permisos_id == 1 %}
                                    Administrador
                                {% elif usuario.permisos_id == 4 %}
                                    Usuario Root
                                {% else %}
                                    Colaborador
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="inputEmail4" style="color: aliceblue; font-weight: bold;">Correo</label>
                        <div class="card">
                            <div class="card-body" style="width: 100%;">
                                {{ usuario.correo }}
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="nombre" class="form-label">Nombre</label>
                        <input type="text" class="form-control" id="nombre" name="nombre" value="{{ usuario.nombre }}" style='height: 4rem;'>
                    </div>
                    <div class="mb-3">
                        <label for="descripcion" class="form-label">Descripción</label>
                        <input type="text" class="form-control" id="descripcion" name="descripcion" value="{{ usuario.descripcion }}" style='height: 4rem;'>

                    </div>
                    <div class="mb-3">
                        <label for="foto_perfil" class="form-label">Selecciona una nueva foto de perfil</label>
                        <select id="id_foto_perfil" name="foto_perfil" class="form-control">
                            {% for foto in fotos_perfil %}
                                <option value="{{ foto.pk }}" {% if foto.pk == usuario.foto_perfil.pk %}selected{% endif %} data-img-url="{{ foto.direccion.url }}">{{ foto.nombre }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="mb-3">
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-success" name="editar_perfil">CONFIRMAR CAMBIOS Y EDITAR PERFIL</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
    
    <br>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const fotoPerfilDropdown = document.getElementById('id_foto_perfil');
            const fotoPerfilPreview = document.getElementById('foto-perfil-preview');

            fotoPerfilDropdown.addEventListener('change', function() {
                const selectedFotoPerfil = fotoPerfilDropdown.options[fotoPerfilDropdown.selectedIndex];
                const fotoPerfilUrl = selectedFotoPerfil.getAttribute('data-img-url');
                fotoPerfilPreview.src = fotoPerfilUrl;
            });
        });
    </script>

{% endblock %}

mainapp/templates/mainapp/perfil_colaborador.html
{% extends 'mainapp/base.html' %}
{% load form_extras %}
{% load static %} <!-- Cargar el tag static -->
{% get_media_prefix as media_prefix %}

{% block title %}PERFIL{% endblock %}

{% block content %}

<div class='container'>
    <div class="row g-2">
        <div class="col-md">
            <div class="form-floating">
                <div class="mb-3">
                    <div class="card" style="width: 32rem; border-radius: 10px;">
                        <img class="card-img-top" src="{{ colaborador.foto_perfil.direccion.url }}" alt="Foto de perfil" style="border-radius: 10px;" id="foto-perfil-preview">
                        <div class="card-body">
                            <h5 class="card-title" style="font-weight: bold;">{{ colaborador.nombre }}</h5>
                            <p class="card-text">{{ colaborador.correo }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md">
            <div class="form-floating">
                <div class="mb-3">
                    <label for="inputEmail4" style="color: aliceblue; font-weight: bold;">Correo</label>
                    <div class="card">
                        <div class="card-body" style="width: 100%;">
                            {{ colaborador.correo }}
                        </div>
                    </div>
                </div>
                <div class="mb-3">
                    <label for="nombre" class="form-label">Nombre</label>
                    <input type="text" class="form-control" id="nombre" name="nombre" value="{{ colaborador.nombre }}" style='height: 4rem;'>
                </div>
                <div class="mb-3">
                    <label for="descripcion" class="form-label">Descripción</label>
                    <input type="text" class="form-control" id="descripcion" name="descripcion" value="{{ colaborador.descripcion }}" style='height: 4rem;'>
                </div>
            </div>
        </div>
    </div>
</div>

    <br>
{% endblock %}

